package hzst.android.form;

public interface Field {
	String APPROVE_WORKFLOWNAME = "WORKFLOWNAME";
	String APPROVE_TABLENAME = "TABLENAME";
	String APPROVE_RECORDID = "RECORDID";
	String APPROVE_TASKID = "TASKID";
	String APPROVE_CREATEDEPTID = "CREATEDEPTID";
	String APPROVE_CREATEUSERID = "CREATEUSERID";
	String APPROVE_CREATEDEPTNAME = "CREATEDEPTNAME";
	String APPROVE_CREATEMEMBERNAME = "CREATEMEMBERNAME";

	String APPROVE_ISEDITABLE = "editable";

}
